[tool.poetry]
name = "runner"
version = "0.1.0"
description = ""
authors = ["Nihal Anand <nihalbanand@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
cx-freeze = "^6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
